name: Vitals
version: '${version}'
main: com.marco.vitals.Vitals
api-version: 1.19
commands:
  gamemode:
    description: Change player gamemode.
    aliases: [gm, gmc, gms, gma, gmsp]
    usage: /<command> [gamemode] [target]
  tp:
    description: Teleport to a player.
    aliases: [teleport]
    usage: /<command> <player> [target]
  back:
    description: Teleport to your location prior to teleporting.
    aliases: [return]
    useage: /<command> [player]
  overseer:
    description: Toggle overseer.
    aliases: [os, toggleoverseer]
    usage: /<command>
