name: Vitals
version: '${version}'
main: com.marco.vitals.Vitals
api-version: 1.19
commands:
  gamemode:
    description: Change player gamemode.
    aliases: [gm, gmc, gms, gma, gmsp]
    usage: /<command> [gamemode] [target]
    permission: vitals.gamemode
  overseer:
    description: Toggle overseer.
    aliases: [os, toggleoverseer]
    usage: /overseer
    permission: vitals.overseer